export const enum ENV_VARIABLE_NAMES {
  DATABASE_URL = 'DATABASE_URL',
  ACCESS_JWT_SECRET = 'ACCESS_JWT_SECRET',
  REFRESH_JWT_SECRET = 'REFRESH_JWT_SECRET',
  ACCESS_JWT_PERIOD = 'ACCESS_JWT_PERIOD',
  REFRESH_JWT_PERIOD = 'REFRESH_JWT_PERIOD',
  TEST = 'TEST',
  DEV = 'DEV',
}
export const PORT = 3000;
