export const enum ENV {
  DATABASE_URL = 'DATABASE_URL',
  ACCESS_JWT_SECRET = 'ACCESS_JWT_SECRET',
  REFRESH_JWT_SECRET = 'REFRESH_JWT_SECRET',
  ACCESS_JWT_PERIOD = 'ACCESS_JWT_PERIOD',
  REFRESH_JWT_PERIOD = 'REFRESH_JWT_PERIOD',
}
